apiVersion: batch/v1
kind: Job
metadata:
  name: hamer-demo
spec:
  template:
    spec:
      nodeSelector:
        node-pool-type: gpu-pool
      containers:
      - name: hamer-demo
        image: gcr.io/lagorgeous-helping-hands/hamer:latest
        command:
        - /bin/sh
        - -c
        - "mkdir -p /mnt/nfs/jobs && python demo.py --img_folder /mnt/nfs/test_frames --out_folder /mnt/nfs/out_demo --batch_size 48 --checkpoint /mnt/nfs/_DATA/hamer_ckpts/checkpoints/hamer.ckpt --data_dir /mnt/nfs/_DATA 2>&1 | tee /mnt/nfs/jobs/hamer-demo.log"
        resources:
          limits:
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: nfs-storage
          mountPath: /mnt/nfs
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: filestore-pvc
      restartPolicy: OnFailure
