apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestore-pv
spec:
  capacity:
    storage: 1024Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: filestore-csi
  csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle: "172.27.84.82:/fileshare"
    volumeAttributes:
      ip: "172.27.84.82"
      volume: "fileshare"
