apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestore-pv
spec:
  capacity:
    storage: 1024Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: filestore-csi
  csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle: "10.59.124.226:/fileshare"
    volumeAttributes:
      ip: "10.59.124.226"
      volume: "fileshare"
