apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filestore-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: filestore-csi
  volumeName: filestore-pv
  resources:
    requests:
      storage: 1024Gi
