apiVersion: batch/v1
kind: Job
metadata:
  name: twitch-recorder-petewang-xyz-1729737123
spec:
  template:
    spec:
      nodeSelector:
        node-pool-type: default-pool
      containers:
      - name: stream-recorder
        image: gcr.io/lagorgeous-helping-hands/stream-recorder:latest
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command:
        - /bin/sh
        - -c
        - |
          ./record_twitch.sh "https://www.twitch.tv/petewang_xyz" "/mnt/nfs/streams/petewang-xyz-1729737123/videos" "petewang_xyz" 2>&1 | tee /mnt/nfs/jobs/twitch-recorder/${POD_NAME}.log
        volumeMounts:
        - name: nfs-storage
          mountPath: /mnt/nfs
      restartPolicy: Never
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: filestore-pvc
  backoffLimit: 4
