# kubernetes/rtmp.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: rtmp-conf
data:
  nginx.conf: |
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    # RTMP server configuration
    rtmp {
        server {
            listen 1935;
            chunk_size 4096;

            # This application is for live streaming
            application live {
                live on;
                record all;
                record_path /mnt/nfs/recordings;
                record_unique on;
                hls_sync 1ms;

                # HLS settings for viewing streams in a web browser
                hls on;
                hls_path /mnt/nfs/hls;
                hls_fragment 3s;
                hls_playlist_length 60s;
            }
        }
    }

    # HTTP server for HLS playback
    http {
        server {
            listen 8080;

            location /hls {
                # Serve HLS files
                types {
                    application/vnd.apple.mpegurl m3u8;
                    video/mp2t ts;
                }
                alias /mnt/nfs/hls;
                add_header Cache-Control no-cache;
                # CORS headers to allow playback from any domain
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
                add_header 'Access-Control-Allow-Headers' 'Range';
                if ($request_method = 'OPTIONS') {
                    add_header 'Access-Control-Allow-Origin' '*';
                    add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
                    add_header 'Access-Control-Allow-Headers' 'Range';
                    add_header 'Content-Length' 0;
                    return 204;
                }
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtmp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtmp-server
  template:
    metadata:
      labels:
        app: rtmp-server
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-11-21T01:06:00Z" # Force rollout
    spec:
      containers:
      - name: rtmp-server
        image: tiangolo/nginx-rtmp
        command: ["/bin/sh", "-c", "mkdir -p /mnt/nfs/recordings && chmod -R 777 /mnt/nfs/hls /mnt/nfs/recordings && nginx -g 'daemon off;'"]
        securityContext:
          runAsUser: 0 # Run as root to ensure write permissions
          allowPrivilegeEscalation: true # Required for runAsUser 0 in some setups
        ports:
        - containerPort: 1935
        - containerPort: 8080
        volumeMounts:
        - name: rtmp-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nfs-storage
          mountPath: /mnt/nfs
      - name: gcs-uploader
        image: google/cloud-sdk:slim
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "Scanning for recordings to move to GCS..."
            for FLV_FILE in /mnt/nfs/recordings/*.flv; do
              if [ -f "$FLV_FILE" ]; then
                FILENAME=$(basename "$FLV_FILE")
                # Strip timestamp and .flv extension. Assumes filename is stream_key-timestamp.flv
                STREAM_KEY=$(echo "$FILENAME" | sed -E 's/-[0-9]+\.flv$//')

                case "$STREAM_KEY" in
                  *_camera-*)
                    STREAM_NAME=$(echo "$STREAM_KEY" | sed -E 's/(.*)_camera-([0-9]+)/\1/')
                    CAMERA_NUM=$(echo "$STREAM_KEY" | sed -E 's/(.*)_camera-([0-9]+)/camera-\2/')
                    TARGET_GCS_PATH="gs://multi-camera-streams/${STREAM_NAME}/${CAMERA_NUM}/"

                    echo "Moving file $FLV_FILE to $TARGET_GCS_PATH"
                    gsutil mv "$FLV_FILE" "${TARGET_GCS_PATH}"

                    if [ $? -eq 0 ]; then
                      echo "Successfully moved file."
                    else
                      echo "Warning: Failed to move file $FLV_FILE. Will retry later."
                    fi
                    ;;
                  *)
                    echo "Warning: Skipping file $FLV_FILE, stream key format not recognized from filename: $FILENAME"
                    ;;
                esac
              fi
            done
            echo "Scan complete. Waiting 60 seconds."
            sleep 60
          done
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/gcs-credentials/gcp-credentials.json
        volumeMounts:
        - name: nfs-storage
          mountPath: /mnt/nfs
        - name: gcs-credentials
          mountPath: /etc/gcs-credentials
          readOnly: true
      volumes:
      - name: rtmp-conf
        configMap:
          name: rtmp-conf
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: filestore-pvc
      - name: gcs-credentials
        secret:
          secretName: gcs-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: rtmp-service
spec:
  type: LoadBalancer
  selector:
    app: rtmp-server
  ports:
  - name: rtmp
    protocol: TCP
    port: 1935
    targetPort: 1935
  - name: http-hls
    protocol: TCP
    port: 8080
    targetPort: 8080