apiVersion: v1
kind: Pod
metadata:
  name: shell
spec:
  containers:
  - name: shell
    image: google/cloud-sdk:slim
    command: ['sleep', '3600']
    volumeMounts:
    - name: nfs-volume
      mountPath: "/mnt/nfs"
  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: filestore-pvc